### ISSUE TITLE
Remove Edge from ignore rules

### ISSUE THREAD

**Issue by 03c** [LGUG2Z/komorebi-application-specific-configuration#116]
In order to get Edge to work, I have added the following to my komorebi.json config:

```
"manage_rules": [
    {
      "kind": "Exe",
      "id": "msedge.exe",
      "matching_strategy": "Equals"
    },
    {
      "kind": "Class",
      "id": "Chrome_WidgetWin_2",
      "matching_strategy": "Equals"
    }
  ]
```

I think the corresponding ignore rules should be removed from the applications.json config. Happy to put in a PR if this is correct.

**Comment by LGUG2Z** [comment]
Can you please try updating to the latest version of the JSON file (`komorebic fetch-asc`) and restarting komorebi first?

In my initial commit adding Edge yesterday I mistakenly left out the array syntax for the composite rule, which I fixed in a later commit.

In the earlier commit Edge was indeed failing to tile at all, but adding the correct composite rule syntax fixed this while also successfully hiding the ghost tiles that appear when watching YouTube videos.
